Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Max: 20
  ExcludedMethods: []

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/MethodLength:
  CountComments: false
  Max: 50

Metrics/ModuleLength:
  CountComments: false
  Max: 300
