source 'https://rubygems.org'

ruby '3.2.0'

gem 'pg'#, '1.1.4'
gem 'rake'#, '12.3.3'
gem 'rack-flash3'#, '1.0.5'
gem 'require_all'#, '1.4.0'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-cross_origin'
gem 'rack'#, '2.1.4'
gem 'bcrypt'#, '3.1.13'
gem 'ancestry'#, '3.2.1'
gem 'pagy'
gem 'racksh'
gem 'paranoia'
gem 'webrick'
# gem 'sqlite3', '1.3.13'
